# Stage 1: Build the React app using Node.js
FROM gplane/pnpm:8-node18-bullseye as build

WORKDIR /app

# Copy the rest of the application code
COPY . .

# Build the React app
RUN pnpm install
RUN pnpm run build

# Stage 2: Serve the React app using Nginx
FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
# Copy the built app from the previous stage
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
